services:
  - type: web
    name: liren-map-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3000

databases:
  - name: liren-map-db
    plan: free
    databaseName: liren
